algoritmo "Print salteando linha junto com variáveis" // Titulo do código

var x: caractere // Definição da variável X e o seu tipo de variável

inicio // Define a função Início

    x <- "teste" // Atribui 

    escreval("Olá Mundo!")
    escreval(x, "ok")           // Escreve: teste ok (e depois pula linha)
    escreval(x, " ok")          // Escreve: teste  ok (e depois pula linha)
    escreva(x + " ok")          // Escreve: teste ok (e depois pula linha)

fimalgoritmo